version: '3.8'

services:
  # ?? Veritaban: PostgreSQL
  # Sipari ve Urun katalog verileri iin
  postgres:
    image: postgres:15-alpine
    container_name: micro_postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: micro_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  # ?? Mesaj Kou: RabbitMQ
  # Servisler aras asenkron haberlesme iin
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: micro_rabbitmq
    ports:
      - "5672:5672"   # Mesaj kuyruu portu
      - "15672:15672" # WebView Yönetim Paneli
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  # ?? Cache Katman: Redis
  # Yuksek performanslı veri saklama iin
  redis:
    image: redis:7-alpine
    container_name: micro_redis
    ports:
      - "6379:6379"

volumes:
  pgdata:
