version: '3.8'

services:
  # ?? API Gateway: Sistemin Zrhlı Kapısı
  gateway-service:
    build:
      context: ./services/gateway-service
    container_name: micro_gateway
    ports:
      - "8080:8080" # Dıs dunyaya acılacak tek port
    depends_on:
      - product-service
      - order-service
    networks:
      - micro_network

  # ?? Product Service
  product-service:
    build:
      context: ./services/product-service
    container_name: micro_product
    # Eksık: port mapping kaldırıldı (Dısarıdan erısım kapalı)
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - micro_network

  # ?? Order Service
  order-service:
    build:
      context: ./services/order-service
    container_name: micro_order
    # Eksık: port mapping kaldırıldı (Dısarıdan erısım kapalı)
    depends_on:
      product-service:
        condition: service_started
    networks:
      - micro_network

  # ?? Veritaban: PostgreSQL
  postgres:
    image: postgres:15-alpine
    container_name: micro_postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: micro_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d micro_db"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - micro_network

  # ?? Mesaj Kou: RabbitMQ
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: micro_rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 10s
      timeout: 10s
      retries: 5
    networks:
      - micro_network

  # ?? Cache Katman: Redis
  redis:
    image: redis:7-alpine
    container_name: micro_redis
    ports:
      - "6379:6379"
    networks:
      - micro_network

networks:
  micro_network:
    driver: bridge

volumes:
  pgdata:
